### PR TITLE
Fixes #14 - Update bootstrap table

### LINKED ISSUE #14: react-bootstrap-table is deprecated
**react-bootstrap-table** is _deprecated_ as per [their homepage](http://allenfang.github.io/react-bootstrap-table/index.html),  instead react-bootstrap-table2 should be used.

### PR DESCRIPTION
**Pull request by pritam-patil**
Changes:
- Removed `react-bootstrap-table` as it is deprecated
- Added `react-bootstrap-table-next` as its replacement
- Added corresponding packages for pagination and filters
- Updated respective css to match older UX

Other additions:
- Showing total number of rows to know
  number of rows shown, remaining

### CODE REVIEW

**Comment by jmuzsik** [comment]
Wow, @pritam-patil, this is awesome. I'll look at it quick. Really appreciate it! 

If you want to add new features, alter the UX or design. Anything of the sort, by all means go ahead and do it!

If you're interested in changing up the backend as well, let me know. Any suggestions are welcome.

An example request looks like this: https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues so that is the data we have to work with for each issue.

**Comment by jmuzsik** [comment]
@pritam-patil There are a couple things to fix in this PR.

For one, Case Sensitive Language Search does not work any longer. In the original app you can search for ts or TS for typescript or the like. Notice the problems in the developer tools (command + option + i on a macbook) to fix this. Let me know if you need help.

The other thing is that the information about the rows is aligned completely to the left of the screen, center it more as it is in the original site... you can do that with flexbox.

**Comment by pritam-patil** [comment]
@jMuzsik - Thanks for finding the issue with case sensitivity, I seem to have missed that previously it was 'like' and 'eq' and this change expects a boolean. 
Regarding the styles for columns, I don't seem to reproduce the issue. Should you think you have the time for it, pls make the necessary changes. Otherwise let me know. Thanks.

**Comment by pritam-patil** [comment]
@jMuzsik - I've added the fix for case sensitivity issue. Pls check. Thanks.

**Comment by jmuzsik** [comment]
Looks good! Thanks a lot @pritam-patil !

**Pull request merged**
